plugins {
    id 'com.android.application' version '9.4.1' apply false
    id 'app.cash.paparazzi' version '2.0.0-alpha05' apply false
    id 'org.sonarqube' version '7.5.0.8588'
}

sonar {
    properties {
        property 'sonar.projectKey', 'KSmanis_QTTT'
        property 'sonar.organization', 'ksmanis'
    }
}

project(':app') {
    sonar {
        properties {
            property 'sonar.coverage.jacoco.xmlReportPaths', layout.buildDirectory.file('reports/coverage/test/debug/report.xml').get().asFile
        }
    }
}

tasks.named('sonar') {
    dependsOn ':app:createDebugUnitTestCoverageReport'
}

tasks.register('clean', Delete) {
    delete getLayout().getBuildDirectory()
}
