buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.4.0'
        classpath 'app.cash.paparazzi:paparazzi-gradle-plugin:2.0.0-alpha05'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

tasks.register('clean', Delete) {
    delete getLayout().getBuildDirectory()
}
