min_version = "2026.9.7"

[settings]
java.shorthand_vendor = "temurin"

[tasks]
test = { depends = ["test:*"] }
"test:assembleDebug" = "./gradlew :app:${MISE_TASK_NAME#test:}"
"test:bundleRelease" = "./gradlew :app:${MISE_TASK_NAME#test:}"
"test:compileOpeningBookGenerator" = "./gradlew :app:${MISE_TASK_NAME#test:}"
"test:lintDebug" = "./gradlew :app:${MISE_TASK_NAME#test:}"
"test:pixel2Api27DebugAndroidTest" = "./gradlew :app:${MISE_TASK_NAME#test:}"
"test:pixel2Api36DebugAndroidTest" = "./gradlew :app:${MISE_TASK_NAME#test:}"
"test:pixel2Api37DebugAndroidTest" = "./gradlew :app:${MISE_TASK_NAME#test:}"
"test:verifyPaparazziDebug" = "./gradlew :app:${MISE_TASK_NAME#test:}"

[tools]
google-java-format = "1.36.1"
java = "25.0.4+101.0.LTS"
prek = { depends = ["google-java-format"], version = "0.5.3" }
