name: test
on: [pull_request, push, workflow_dispatch]
concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
permissions:
  contents: read
jobs:
  gradle:
    name: ${{ matrix.id }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        id:
          - assembleDebug
          - bundleRelease
          - compileOpeningBookGenerator
          - lintDebug
          - pixel2Api27DebugAndroidTest
          - pixel2Api36DebugAndroidTest
          - pixel2Api37DebugAndroidTest
          - verifyPaparazziDebug
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          install_args: java
      - name: Set up Android SDK
        uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699 # v4.0.1
        with:
          log-accepted-android-sdk-licenses: false
          packages: ${{ matrix.id == 'pixel2Api27DebugAndroidTest' && 'emulator' || '' }} platform-tools
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
      - name: Enable KVM
        if: contains(matrix.id, 'DebugAndroidTest')
        run: sudo chmod 666 /dev/kvm
      - name: Run Gradle task
        run: >-
          ./gradlew --no-daemon
          ${{ contains(matrix.id, 'DebugAndroidTest') && '-Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect' || '' }}
          :app:${{ matrix.id }}
      - name: Upload Android test reports
        if: failure() && contains(matrix.id, 'DebugAndroidTest')
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: android-test-reports-${{ matrix.id }}
          path: |
            app/build/reports/androidTests/managedDevice/**
            app/build/outputs/androidTest-results/managedDevice/**
